apiVersion: v1
kind: Service
metadata:
  name: vitservice
spec:
  ports:
  - port: 80
  selector:
    app: vitweb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitdeployment
spec:
  selector:
    matchLabels:
      app: vitweb
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: vit-web
    spec:
      containers:
      - name: vitweb
        image: acraeakstraining.azurecr.io/vit-web:1.1
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: helloapp